
package hds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FailToLogRequestException", targetNamespace = "http://hds/")
public class FailToLogRequestException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FailToLogRequestException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FailToLogRequestException_Exception(String message, FailToLogRequestException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FailToLogRequestException_Exception(String message, FailToLogRequestException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: hds.FailToLogRequestException
     */
    public FailToLogRequestException getFaultInfo() {
        return faultInfo;
    }

}
