
package hds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HDSServer", targetNamespace = "http://hds/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HDSServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InvalidInputException_Exception
     */
    @WebMethod
    @Action(input = "http://hds/HDSServer/registerRequest", output = "http://hds/HDSServer/registerResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://hds/HDSServer/register/Fault/InvalidInputException")
    })
    public void register(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws InvalidInputException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InvalidInputException_Exception
     */
    @WebMethod(operationName = "send_amount")
    @Action(input = "http://hds/HDSServer/send_amountRequest", output = "http://hds/HDSServer/send_amountResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://hds/HDSServer/send_amount/Fault/InvalidInputException")
    })
    public void sendAmount(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws InvalidInputException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InvalidInputException_Exception
     */
    @WebMethod(operationName = "receive_amount")
    @Action(input = "http://hds/HDSServer/receive_amountRequest", output = "http://hds/HDSServer/receive_amountResponse", fault = {
        @FaultAction(className = InvalidInputException_Exception.class, value = "http://hds/HDSServer/receive_amount/Fault/InvalidInputException")
    })
    public void receiveAmount(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws InvalidInputException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns hds.CheckResult
     */
    @WebMethod(operationName = "check_account")
    @WebResult(partName = "return")
    @Action(input = "http://hds/HDSServer/check_accountRequest", output = "http://hds/HDSServer/check_accountResponse")
    public CheckResult checkAccount(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns hds.AuditResult
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://hds/HDSServer/auditRequest", output = "http://hds/HDSServer/auditResponse")
    public AuditResult audit(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
